export const defaultCategories = [
  // Income
  {
    id: "salary",
    name: "Salary",
    type: "INCOME",
    colors: "bg-green-500/10 text-green-500",
    icon: "Wallet",
  },
  {
    id: "freelance",
    name: "Freelance",
    type: "INCOME",
    colors: "bg-cyan-500/10 text-cyan-500",
    icon: "Laptop",
  },
  {
    id: "investments",
    name: "Investments",
    type: "INCOME",
    colors: "bg-indigo-500/10 text-indigo-500",
    icon: "TrendingUp",
  },
  {
    id: "business",
    name: "Business",
    type: "INCOME",
    colors: "bg-pink-500/10 text-pink-500",
    icon: "Building",
  },
  {
    id: "rental",
    name: "Rental",
    type: "INCOME",
    colors: "bg-orange-500/10 text-orange-500",
    icon: "Home",
  },
  {
    id: "other-income",
    name: "Other Income",
    type: "INCOME",
    colors: "bg-gray-500/10 text-gray-500",
    icon: "Plus",
  },

  // Expense
  {
    id: "housing",
    name: "Housing",
    type: "EXPENSE",
    colors: "bg-red-500/10 text-red-500",
    icon: "Home",
    subcategories: ["Rent", "Mortgage", "Property Tax", "Maintenance"],
  },
  {
    id: "transportation",
    name: "Transportation",
    type: "EXPENSE",
    colors: "bg-orange-500/10 text-orange-500",
    icon: "Car",
    subcategories: ["Fuel", "Public Transit", "Insurance", "Auto Maintenance"],
  },
  {
    id: "groceries",
    name: "Groceries",
    type: "EXPENSE",
    colors: "bg-green-500/10 text-green-500",
    icon: "ShoppingBasket",
  },
  {
    id: "dining",
    name: "Dining Out",
    type: "EXPENSE",
    colors: "bg-rose-500/10 text-rose-500",
    icon: "UtensilsCrossed",
  },
  {
    id: "utilities",
    name: "Utilities",
    type: "EXPENSE",
    colors: "bg-cyan-500/10 text-cyan-500",
    icon: "Zap",
    subcategories: ["Electricity", "Water", "Gas", "Internet", "Phone"],
  },
  {
    id: "entertainment",
    name: "Entertainment",
    type: "EXPENSE",
    colors: "bg-violet-500/10 text-violet-500",
    icon: "Film",
    subcategories: ["Movies", "Games", "Streaming Services"],
  },
  {
    id: "shopping",
    name: "Shopping",
    type: "EXPENSE",
    colors: "bg-pink-500/10 text-pink-500",
    icon: "ShoppingBag",
    subcategories: ["Clothing", "Electronics", "Home Goods"],
  },
  {
    id: "healthcare",
    name: "Healthcare",
    type: "EXPENSE",
    colors: "bg-teal-500/10 text-teal-500",
    icon: "HeartPulse",
    subcategories: ["Medical", "Dental", "Pharmacy", "Insurance"],
  },
  {
    id: "education",
    name: "Education",
    type: "EXPENSE",
    colors: "bg-indigo-500/10 text-indigo-500",
    icon: "GraduationCap",
    subcategories: ["Tuition", "Books", "Courses"],
  },
  {
    id: "personal",
    name: "Personal Care",
    type: "EXPENSE",
    colors: "bg-fuchsia-500/10 text-fuchsia-500",
    icon: "Smile",
    subcategories: ["Haircut", "Cosmetics", "Spa"],
  },
  {
    id: "travel",
    name: "Travel",
    type: "EXPENSE",
    colors: "bg-sky-500/10 text-sky-500",
    icon: "Plane",
  },
  {
    id: "insurance",
    name: "Insurance",
    type: "EXPENSE",
    colors: "bg-slate-500/10 text-slate-500",
    icon: "Shield",
    subcategories: ["Life", "Home", "Auto"],
  },
  {
    id: "gifts",
    name: "Gifts & Donations",
    type: "EXPENSE",
    colors: "bg-rose-500/10 text-rose-500",
    icon: "Gift",
  },
  {
    id: "bills",
    name: "Bills & Fees",
    type: "EXPENSE",
    colors: "bg-orange-500/10 text-orange-500",
    icon: "Receipt",
    subcategories: ["Bank Fees", "Late Fees", "Service Charges"],
  },
  {
    id: "other-expense",
    name: "Other Expense",
    type: "EXPENSE",
    colors: "bg-gray-500/10 text-gray-500",
    icon: "MoreHorizontal",
  },
];

export const categoryColors = defaultCategories.reduce((acc, category) => {
  acc[category.id] = category.colors;
  return acc;
}, {});
